### ISSUE TITLE
Duplicate input when launching steam

### ISSUE THREAD

**Issue by rym002** [rodrigorc/inputmap#5] opened 2020-03-21 18:02 UTC
When inputmap is running, steam receives duplicate input. Need a way to disconnect or exit inputmap when steam is launched.

**Comment by rodrigorc** [comment] 2020-03-25 09:57
The problem is that hid devices in Linux are multi-user, that is, there is nothing that prevents several processes to read from it at the same time.

Now Steam thinks that it is the only owner of the device, inputmap thinks the same, and there is no easy way to negotiate this.

Frankly, I think that it is out of scope of inputmap to get out of the way when other client is running, be it Steam, xboxdrv or other inputmap instance.

But you can handle this issue with some kind of wrapper:

####  ~/bin/steam:
```
#/bin/bash
killall inputmap
exec /usr/bin/steam
```
Or you can setup both your Steam and inputmap as systemd user units and add a [`Conflicts=` directive](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Conflicts=) there:

> Configures negative requirement dependencies. If a unit has a Conflicts= setting on another unit, starting the former will stop the latter and vice versa.

**Comment by rym002** [comment] 2020-03-28 00:43
Any way to make inputmap exit when the controller is off? It would work for me if the controller is off and then turned on in steam. This appears to work if inputmap is not running and the controller is turned off when steam launches. When steam exits inputmap starts due to the udev rule, then I have to kill the process manually to remove the duplicate input.

**Comment by rodrigorc** [comment] 2020-04-03 17:47
Sorry for the delay in the reply, these days are weird...

I've just tried, and when I disconnect the controller, inputmap just exits. I think the controller is not actually off when steam launches, just that Steam happens not to emulate anything special in desktop mode for you. However, for me it behaves as a mouse.

Or are you talking of a different "off"?

**Comment by rym002** [comment] 2020-04-05 03:55
For me inputmap stays running, does not exit. I am using the wireless controller with the dongle still attached. There is a device "Valve Software Steam Controller" which remains when off.

**Comment by rodrigorc** [comment] 2020-04-05 11:20
> ... I am using the wireless controller...

Ah, the good old wireless adaptor, I have mine somewhere...

I've added d753409bac5646908df839e025d9eff4aeda59f9 to master that forces the program to exit when it receives a power-off event. Let me know if it works for you.

Would it make sense to add a parameter to the configuration file to make this optional? What do you think?

**Comment by rym002** [comment] 2020-04-11 02:24
That worked. Configurable is always good to allow others to flexibility. 

Thanks for the quick turnaround.

**Closed as completed** 2020-04-12 18:06 UTC
